// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjnrknnxohouebhjunor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbnJrbm54b2hvdWViaGp1bm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODI1NzcsImV4cCI6MjA2MjM1ODU3N30.MjZEQalhc7IJTAEK-omnA2ZXtj-BKGxfESi6RAsZP8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);